n = str(input('Digite seu nome completo: ')).strip()
nome = n.split() 
print('Muito pazer em te conhecer!')
print('Seu Primeiro nome é {}'.format(nome[0]))
print('Seu ultimo nome é {}'.format(nome[len(nome)-1]))